### ISSUE TITLE
Contributor's Guide

### ISSUE THREAD

**Issue by tracheopteryx** [iearn-finance/yearn-docs#85]
@arcturus:
Goal: Make it as easy as possible for anyone (devs/designers/writers) to contribute to Yearn

Motivation: As it stands, it is difficult for someone new coming to Yearn with an idea/bug/general skills to know how to best contribute.

Current Draft: https://hackmd.io/Cq6OF2amQ_ypTHvivJ7H0Q?view

Using maker contributor's page as inspiration/guide https://community-portal-staging.makerfoundation.com/en/work_with_us/content/contributor-tools

Needs Elaboration:
1) Documentation
2) Developers

3) Designers
4) Filing Bugs

**Comment by Faolain** [comment]
Added some prerequisite docs for Contribute as well which are heavily (and I mean stress **heavily**) inspired and/or copied from Maker Comm Dev documentation. 

**Writing Style Guide:**https://hackmd.io/dXQecpkJQX6XRy4y7k7j3g
**How to Use GIthub: (to contribute to docs)**https://hackmd.io/4U35op0ORoGT24lzPhbGNQ
**Reviewer Guide: https://hackmd.io/juTKNn3xTpKJgFDo2AglLw

**Comment by Wot-Is-Goin-On** [comment]
Under the"Documentation" heading we could show the documentation structure first so that people know what docs we intend to produce.
https://docs.google.com/document/d/1C2BYgun2q2dP_f39q14pshsaeuz92XKlvQV5PpUSCUc/edit?usp=sharing
The current draft addresses the "how" to contribute (e.g. use Hackmd and Github) whereas a nice diagram of the docs we're producing addresses the "what" to contribute.
